packages:
  - apps/*
  - packages/*

autoInstallPeers: true

catalog:
  "@ckb-ccc/core": "1.12.5"
  "@eslint/js": ^10
  "@hugeicons/core-free-icons": ^4
  "@hugeicons/react": ^1
  "@ledgerhq/hw-transport": "6.35.4"
  "@ledgerhq/hw-transport-webhid": "6.35.4"
  "@multiformats/multiaddr": "13.0.3"
  "@nervosnetwork/fiber-js": "0.8.1"
  "@noble/curves": "2.2.0"
  "@scure/bip32": "2.2.0"
  "@types/node": ^26
  "@types/react": ^19
  "@types/react-dom": ^19
  "@vitejs/plugin-react": ^6
  "bip32-path": "0.4.2"
  "ckb-light-client-js": "1.0.3"
  dayjs: ^1
  eslint: ^10
  i18next: ^26
  jsdom: ^29
  prettier: ^3
  prettier-plugin-tailwindcss: ^0.8
  react: ^19
  react-dom: ^19
  react-i18next: ^17
  tailwindcss: ^4
  typescript: ^6
  typescript-eslint: ^8
  vite: ^8
  vite-plugin-svgr: ^5
  vitest: ^4
  wrangler: ^4

hoist: true

nodeLinker: hoisted

onlyBuiltDependencies:
  - esbuild
  - msw
  - node-hid
  - secp256k1
  - usb

overrides:
  "@ckb-ccc/core": "1.12.5"

preferFrozenLockfile: true
