/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as ConnectRouteImport } from './routes/connect'
import { Route as AuthenticatedRouteImport } from './routes/_authenticated'
import { Route as AuthenticatedIndexRouteImport } from './routes/_authenticated/index'
import { Route as AuthenticatedTransactionsRouteImport } from './routes/_authenticated/transactions'
import { Route as AuthenticatedSendRouteImport } from './routes/_authenticated/send'
import { Route as AuthenticatedDaoRouteImport } from './routes/_authenticated/dao'

const ConnectRoute = ConnectRouteImport.update({
  id: '/connect',
  path: '/connect',
  getParentRoute: () => rootRouteImport,
} as any).lazy(() => import('./routes/connect.lazy').then((d) => d.Route))
const AuthenticatedRoute = AuthenticatedRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedIndexRoute = AuthenticatedIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AuthenticatedRoute,
} as any).lazy(() =>
  import('./routes/_authenticated/index.lazy').then((d) => d.Route),
)
const AuthenticatedTransactionsRoute =
  AuthenticatedTransactionsRouteImport.update({
    id: '/transactions',
    path: '/transactions',
    getParentRoute: () => AuthenticatedRoute,
  } as any).lazy(() =>
    import('./routes/_authenticated/transactions.lazy').then((d) => d.Route),
  )
const AuthenticatedSendRoute = AuthenticatedSendRouteImport.update({
  id: '/send',
  path: '/send',
  getParentRoute: () => AuthenticatedRoute,
} as any).lazy(() =>
  import('./routes/_authenticated/send.lazy').then((d) => d.Route),
)
const AuthenticatedDaoRoute = AuthenticatedDaoRouteImport.update({
  id: '/dao',
  path: '/dao',
  getParentRoute: () => AuthenticatedRoute,
} as any).lazy(() =>
  import('./routes/_authenticated/dao.lazy').then((d) => d.Route),
)

export interface FileRoutesByFullPath {
  '/': typeof AuthenticatedIndexRoute
  '/connect': typeof ConnectRoute
  '/dao': typeof AuthenticatedDaoRoute
  '/send': typeof AuthenticatedSendRoute
  '/transactions': typeof AuthenticatedTransactionsRoute
}
export interface FileRoutesByTo {
  '/connect': typeof ConnectRoute
  '/dao': typeof AuthenticatedDaoRoute
  '/send': typeof AuthenticatedSendRoute
  '/transactions': typeof AuthenticatedTransactionsRoute
  '/': typeof AuthenticatedIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/_authenticated': typeof AuthenticatedRouteWithChildren
  '/connect': typeof ConnectRoute
  '/_authenticated/dao': typeof AuthenticatedDaoRoute
  '/_authenticated/send': typeof AuthenticatedSendRoute
  '/_authenticated/transactions': typeof AuthenticatedTransactionsRoute
  '/_authenticated/': typeof AuthenticatedIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/connect' | '/dao' | '/send' | '/transactions'
  fileRoutesByTo: FileRoutesByTo
  to: '/connect' | '/dao' | '/send' | '/transactions' | '/'
  id:
    | '__root__'
    | '/_authenticated'
    | '/connect'
    | '/_authenticated/dao'
    | '/_authenticated/send'
    | '/_authenticated/transactions'
    | '/_authenticated/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  AuthenticatedRoute: typeof AuthenticatedRouteWithChildren
  ConnectRoute: typeof ConnectRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/connect': {
      id: '/connect'
      path: '/connect'
      fullPath: '/connect'
      preLoaderRoute: typeof ConnectRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/': {
      id: '/_authenticated/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedIndexRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/transactions': {
      id: '/_authenticated/transactions'
      path: '/transactions'
      fullPath: '/transactions'
      preLoaderRoute: typeof AuthenticatedTransactionsRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/send': {
      id: '/_authenticated/send'
      path: '/send'
      fullPath: '/send'
      preLoaderRoute: typeof AuthenticatedSendRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/dao': {
      id: '/_authenticated/dao'
      path: '/dao'
      fullPath: '/dao'
      preLoaderRoute: typeof AuthenticatedDaoRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
  }
}

interface AuthenticatedRouteChildren {
  AuthenticatedDaoRoute: typeof AuthenticatedDaoRoute
  AuthenticatedSendRoute: typeof AuthenticatedSendRoute
  AuthenticatedTransactionsRoute: typeof AuthenticatedTransactionsRoute
  AuthenticatedIndexRoute: typeof AuthenticatedIndexRoute
}

const AuthenticatedRouteChildren: AuthenticatedRouteChildren = {
  AuthenticatedDaoRoute: AuthenticatedDaoRoute,
  AuthenticatedSendRoute: AuthenticatedSendRoute,
  AuthenticatedTransactionsRoute: AuthenticatedTransactionsRoute,
  AuthenticatedIndexRoute: AuthenticatedIndexRoute,
}

const AuthenticatedRouteWithChildren = AuthenticatedRoute._addFileChildren(
  AuthenticatedRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  AuthenticatedRoute: AuthenticatedRouteWithChildren,
  ConnectRoute: ConnectRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
