import { numToHex } from "@ckb-ccc/core"
import { MoneyReceive02Icon } from "@hugeicons/core-free-icons"
import { HugeiconsIcon } from "@hugeicons/react"
import { Button, Input } from "@polymeer/ui"
import { useState } from "react"
import { toast } from "sonner"

import { useFiberWorker } from "@/hooks/use-fiber-worker"
import { generatePreimage } from "@/lib/preimage"
import { parseAmount } from "@/lib/utils"
import { useConfigStore } from "@/stores/config.store"
import { useFiberInvoiceStore } from "@/stores/fiber-invoice.store"

const MIN_RECEIVE_FINAL_EXPIRY_DELTA = "0x927c00"

export function FiberCreateInvoice() {
  const network = useConfigStore((s) => s.network)
  const fiberWorker = useFiberWorker()
  const addInvoice = useFiberInvoiceStore((s) => s.addInvoice)

  const [amount, setAmount] = useState("")
  const [invoiceExpiry, setInvoiceExpiry] = useState("10")
  const [isCreating, setIsCreating] = useState(false)

  const handleCreate = async () => {
    if (!amount.trim()) {
      toast.error("Please enter an amount.")
      return
    }
    const expiryMins = Number(invoiceExpiry)
    if (isNaN(expiryMins) || expiryMins < 5 || expiryMins > 60) {
      toast.error("Expiry must be between 5 and 60 minutes.")
      return
    }

    setIsCreating(true)
    try {
      const shannons = parseAmount(amount)
      const hexInvoiceAmount = numToHex(shannons)
      const expirySeconds = Math.floor(expiryMins * 60)
      const hexExpiry = numToHex(expirySeconds)

      const res = await fiberWorker.createInvoice({
        amount: hexInvoiceAmount,
        currency: network === "mainnet" ? "Fibb" : "Fibt",
        description: "invoice generated by polymeer wallet",
        payment_preimage: generatePreimage(),
        expiry: hexExpiry,
        final_expiry_delta: MIN_RECEIVE_FINAL_EXPIRY_DELTA,
        hash_algorithm: "ckb_hash",
      })
      toast.success("Invoice created!")
      addInvoice(network, res)
      setAmount("")
    } catch (err: unknown) {
      const msg = err instanceof Error ? err.message : String(err)
      toast.error("Failed to create invoice: " + msg)
    } finally {
      setIsCreating(false)
    }
  }

  return (
    <div className="flex flex-col gap-3">
      <div className="flex gap-2">
        <div className="bg-background/50 border-border/30 flex min-w-0 flex-1 items-center rounded-xl border px-3">
          <Input
            placeholder="Amount"
            value={amount}
            onChange={(e) => setAmount(e.target.value)}
            className="h-10 border-none bg-transparent text-sm font-bold shadow-none focus-visible:ring-0"
          />
          <span className="text-muted-foreground/40 shrink-0 text-[10px] font-bold">CKB</span>
        </div>
        <div className="bg-background/50 border-border/30 flex w-24 shrink-0 items-center rounded-xl border px-3">
          <Input
            type="number"
            placeholder="10"
            value={invoiceExpiry}
            onChange={(e) => setInvoiceExpiry(e.target.value)}
            className="h-10 w-full border-none bg-transparent text-sm font-bold shadow-none focus-visible:ring-0"
          />
          <span className="text-muted-foreground/40 shrink-0 text-[10px] font-bold uppercase">m</span>
        </div>
      </div>
      <Button
        className="h-10 w-full rounded-xl text-xs font-bold transition-all active:scale-[0.98]"
        onClick={handleCreate}
        disabled={isCreating || !amount.trim()}
      >
        <HugeiconsIcon icon={MoneyReceive02Icon} size={14} className="mr-2" />
        {isCreating ? "Generating…" : "Create Invoice"}
      </Button>
    </div>
  )
}
